"""
shareable constants
"""

questions = [
    "How do I use the SDK to upload a ranking model?",
    "What drift metrics are supported in Arize?",
    "Does Arize support batch models?",
    "Does Arize support training data?",
    "How do I configure a threshold if my data has seasonality trends?",
    "How are clusters in the UMAP calculated? When are the clusters refreshed?",
    "How does Arize calculate AUC?",
    "Can I send truth labels to Arize separately?",
    "How do I send embeddings to Arize?",
    "Can I copy a dashboard?",
    "Can I copy a dashboard to a new space?",
    "How do I configure permissions for GBQ?",
    "How often does Arize query the table for table import jobs?",
    "Can you configure the query interval for table import jobs?",
    "Do you need to have a prediction label for classification models?",
    "Do you need a prediction ID for the training set?",
    "How do you set up PagerDuty alerts?",
    "Does the ingestion job for GBQ tables detect changes in the table schema?",
    "How do I send in extra metadata with each record?",
    "What is the current retention period of the data in Arize (if any), and can we customize this? (e.g. could we choose to set a specific retention period of, say 90-days, so that all data older than 90 days is deleted from Arize systems?)",
    "Does Arize store the individual records (rows) somewhere, or does it only store the aggregations calculated from the data?",
    "What happens if I upload actuals twice?",
    "What format should the prediction timestamp be?",
    "How often do the monitors run and evaluate?",
    "Do we have the ability to resolve a monitor?",
    "Does Arize support Microsoft Teams alerting?",
    "What should I do if I sent in duplicate prediction IDs?",
    "Why does Arize use UMAP over t-SNE?",
    "Can I export a dashboard as PDF?",
    "How does Arize's surrogate explainability model work?",
    "Can I update my predictions or features on Arize?",
    "What happens if my model schema changes after I deploy a new version of the model?",
    "How does Arize integrate with SageMaker?",
    "Does the ingestion job for GBQ tables detect changes in schema?",
    "Can I configure the Arize data sampling policy?",
    "About how long should it take for delayed actuals to link to predictions in the UI?",
    "Can I change strings to numeric in Arize?",
    "What is the definition of a model or a prediction in Arize?",
    "How do I pass in delayed ground truth?",
    "Can I pass in my own metrics within Arize?",
    "How large should my file sizes be when uploading data?",
    "How long does it take to ingest my data?",
    "How do I edit the frequency that my table import job runs?",
    "What permissions are needed to import my files from cloud storage?",
    "How do I grant permissions to import my GBQ table?",
    "Does Arize ingest null values?",
    "Which file or dataframe columns can be null?",
    "What file types are supported for cloud storage uploads?",
    "Is prediction_id required?",
    "How do I need to format timestamps?",
    "Why do I need a timestamp?",
    "What time unit is a timestamp?",
    "Does Arize support timestamps that are pandas format?",
    "Can I create any string format that is a timestamp?",
    "Can I send latent ground truth for ranking models?",
    "Does Arize count duplicate prediction IDs as a single prediction?",
    "Does Arize sample the data on ingestion of files?",
    "When connecting to a table, is the data copied into Arize or does Arize just run off of the table?",
    "Is the entire data set copied when connecting to data in files?",
    "How long does it take for data to show up in the platform?",
    "Does Arize support PSI as a drift metric?",
    "Arize help",
    "Dataset not showing up",
    "Is it possible for me to change the threshold for PSI for the drift tab, as in what I can configure for each monitor?",
    "I don't have actuals",
    "I see data in the data ingestion tab but none of the charts are showing data. What's going wrong?",
    "My monitor's latest status is green even though the chart shows the threshold is crossed. What does this mean?",
    "What is a managed monitor?",
    "What is Euclidean distance? I thought it is the distance between points. What does it mean on the page?",
    "Can I deploy Arize on my own Kubernetes cluster?",
    "How are the records sent to Arize secured? How does Arize handle sensitive data?",
    "Data ingestion page does not show the correct number of records",
    "How do I link my actuals to predictions?",
    "Can I create one FileImporter job with both predictions and latent actuals?",
    "Why is my FileImport job failing on uploading actuals?",
    "What is a score categorical model?",
    "I am sending images with my embeddings but the images don't load. What's going wrong?",
    "I am sending videos in link_to_data but they don't show up. Why?",
    "Does Arize support timeseries data?",
    "Where can I find HIPAA reporting?",
    "How do I get feature importance on data I upload in the File Importer?",
    "How can I move a model from one space to another?",
    "How do I get an Arize API key?",
    "What is a space key?",
    "How do I rotate my credentials?",
    "I can't recover my password, how do I do that?",
    "What is Arize's retention policy?",
    "How do I delete a space?",
    "How do I delete a space and organization?",
    "How do I change my email address?",
    "I sent the wrong records to Arize. How do I delete them?",
    "I sent 8000 records but I only see 1000 in the UI. Why?",
    "I can't find my feature in any of the dropdowns.",
    "How do I use custom metrics on monitors?",
    "How do I unsubscribe from a monitor?",
    "Do predictions from deleted models count against my plan usage?",
    "How do I change current SAML auth to remove the email and only authorize using the first name and last name?",
    "What counts against my plan usage?",
    "What happens if I go over my plan's allocated volume?",
    "What is the change_timestamp on table import?",
    "Do I need to upload timestamps?",
    "How do I load private images into Arize?",
    "What do I do if I sent in a feature whose type changed?",
    "What's the difference between Arize's Pro and Enterprise plans?",
    "How to share customized dashboard?",
    "How to create custom metric for ROI?",
    "Where do I find the API and Space keys?",
    "How can I run Arize on my own hardware?",
    "Is my prediction data shared with any services except for Arize?",
    "How do I change fields on a prediction?",
    "Can I create monitors with an API?",
    "Can I create dashboards with an API?",
    "How do I delete data?",
    "I can't see the points in the UMAP. How do I make the points bigger?",
    "I want to cancel my account. How do I do that?",
    "I want to delete my data. Help.",
    "How do I update my predictions?",
    "The File Importer job failed. How do I restart it?",
    "Does Arize support Snowflake?",
    "How do I ingest CSV data?",
    "How do I get access to my embeddings?",
    "I don't see errors in the SDK, but my records don't show up. How do I troubleshoot?",
    "Can I download my data?",
    "How can I change the threshold of my metric?",
    "How do I duplicate a dashboard?",
    "My monitor is noisy. How do I fix?",
    "How do I download my data?",
    "I got a 200 from my SDK request, but my data never showed up",
    "Is there a way to automatically infer which columns serve which purpose during the ingestion process?",
    "How much does the Arize platform cost and how do you charge?",
    "What is the price of the Arize platform?",
    "How much does Arize charge and how do you price, is it per model?",
    "What would Arize cost annually and what is the likely ROI? I assume it is quite high ROI",
    "Do you have a pricing calculator that can help me understand the price of Arize relative to the various deployment options?",
    "What is the cost of the Arize platform?",
    "Is there cost for Arize beyond an annual subscription price?",
    "What is the price per model or per volume and how much does the price discount as the volume goes up?",
    "What is the annual cost of a VPC deployment option? How does that price scale?",
    "How expensive is the Arize platform and how do you charge?",
    "Does Arize support object segmentation use cases?",
    "If I am using an object segmentation model, should I apply my own segmentation mask to the image before uploading the image, or will the platform do that for me?",
    "Can you give me an example schema I could use for uploading inference data from an image segmentation model?",
    "What's the difference between image segmentation and object detection?",
    "How do you recommend I create embeddings for an object segmentation model?",
    "Is it possible to upload multiple masks for the same image in a segmentation use case?",
    "What evaluation metrics are supported for image segmentation use cases?",
    "Do you have an example image segmentation notebook?",
    "How many classes are supported for image segmentation?",
    "Do you support IoU for image segmentation?",
    "This is a test question?",
    "?",
    "This is a question?",
    "My service is a hosting service designed for hosting your website. You can put your website on our service and host it with accelerated CDN delivery, tracking of usage data for running your website. Our service is one of the best on the internet in terms of delivery and experience.",
    "What is a timestamp?",
    "What is a prediction ID?",
    "What are actuals?",
    "Can I log single events?",
    "Can I log batches of data?",
    "What happens if I don't have ground truths?",
    "Can Arize be deployed inside my own cloud environment?",
    "What data do I need to send to Arize?",
    "What if I don't have a timestamp?",
    "Do I need to send in input features along with my ground truth, if I'm sending my ground truth data later?",
    "What if I don't have my prediction label or prediction score for my training data?",
    "How do I send training data vs production data?",
    "How do I connect Arize to data that exists somewhere else?",
    "What is the validation environment used for?",
    "Can I set permissions for my users?",
    "Can I set up monitors programmatically, or am I only able to set them up through the UI?",
    "How can I get feature importance values?",
    "Do you only support SHAP for feature importance?",
]
